# Generated by Django 4.0.3 on 2022-03-29 17:24

import ckeditor.fields
import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='message',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='message',
            name='message',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='image_url',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
    ]
