# Generated by Django 4.0.3 on 2022-03-30 10:50

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='General',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.TextField(default='Name')),
                ('site_title', models.TextField(default='Portfolio')),
                ('site_info', models.TextField(default='Info')),
                ('site_linkedin', models.TextField(default='#')),
                ('site_github', models.TextField(default='#')),
                ('site_about_me', ckeditor.fields.RichTextField(default='Description')),
                ('site_phone', models.TextField(default='#')),
                ('site_email', models.TextField(default='#')),
            ],
        ),
    ]
